apiVersion: v1
kind: LimitRange
metadata:
  name: standard-limits
  namespace: kw-b2824a-default
spec:
  limits:
    - default:
        cpu: "500m"
        memory: "256Mi"
      defaultRequest:
        cpu: "100m"
        memory: "64Mi"
      max:
        cpu: "2"
        memory: "2Gi"
      min:
        cpu: "50m"
        memory: "32Mi"
      type: Container