/**
 * OpenSCAD model metadata generated by `npm run scad:render`.
 * Stored in `dist/3dmodels/models.json`.
 */
export interface ScadModel {
  id: string;
  title: string;
  scadFile: string;
  previewImage: string | null;
  stlFile: string;
}

/**
 * Props for the `ScadModelDisplay` Astro component.
 */
export interface ScadModelDisplayProps {
  id: string;
}
